repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        name: ruff core_service
        args: [--fix]
        files: ^core_service/
      - id: ruff
        name: ruff auth_service
        args: [--fix]
        files: ^auth_service/


  # JavaScript/TypeScript форматування (Prettier для frontend)
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.2.5
  #   hooks:
  #     - id: prettier
  #       additional_dependencies: [prettier@3.2.5]
  #       files: ^frontend/.*\.(js|jsx|ts|tsx|json|css|md|html)$
