[tool.ruff]
target-version = "py312"
line-length = 120
exclude = ["migrations", "venv", ".venv", "__pycache__", "worker",".git"]

[tool.ruff.lint]
select = ["E", "F", "B", "I"]
ignore = ["E501"]  # якщо не хочеш довжину рядка лінтити

[tool.ruff.format]
quote-style = "double"
